version: '3'
services:
  cliente:
    hostname: cliente
    build: cliente
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix    
    networks: 
      my_network:
        ipv4_address: 192.168.46.150
      



networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.46.0/24