version: '3'
services:
  apache:
    hostname: apache
    build: apache
    ports:
      - "8080:80"
    networks: 
      my_network:
        ipv4_address: 192.168.21.50
        aliases:
          - novositio.lan
          - www.novositio.lan
    volumes:
      - ./novositio.lan:/opt/web/novositio.lan
      - ./apache/tarefa4.conf:/etc/apache2/sites-enabled/tarefa4.conf
      - ./ssl/novositio.pem:/etc/ssl/certs/novositio.pem
      - ./ssl/novositio.key:/etc/ssl/private/novositio.key
  cliente:
    hostname: cliente
    build: cliente
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix    
    networks: 
      my_network:
        ipv4_address: 192.168.21.150
      



networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.21.0/24